In [4]:
import pandas as pd
csvpath = 'https://github.com/eliaskarikas/predictingNHLsalary/blob/master/nhldata.csv?raw=true'
df = pd.read_csv(csvpath,index_col=0)
df

,CLAUSE,EXPIRY,CAP HIT,SALARY,rank,Player,TEAM,AGE,POS,GP,...,xGA,xGF%,W,L,SO,GAA,Sv%,GA60,xGA60,GSAx60
1,NMC,UFA,"$11,642,857","$13,000,000",2,Artemi Panarin,NYR,28,LW,42,...,30.54,65.33,-,-,-,-,-,-,-,-
2,NaN,UFA,"$11,640,250","$15,900,000",3,Auston Matthews,TOR,22,C,52,...,40.53,65.52,-,-,-,-,-,-,-,-
3,NMC,UFA,"$11,500,000","$12,000,000",4,Erik Karlsson,SJS,30,RD,52,...,62.42,50.17,-,-,-,-,-,-,-,-
4,NMC,UFA,"$11,000,000","$10,000,000",5,Drew Doughty,LAK,30,RD,56,...,70.83,49.66,-,-,-,-,-,-,-,-
5,NMC,UFA,"$11,000,000","$12,000,000",6,John Tavares,TOR,29,C,56,...,39.89,63.64,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,NaN,UFA,"$700,000","$700,000",1506,Antti Suomela,TOR,26,C,4,...,0.97,57.08,-,-,-,-,-,-,-,-
1506,NaN,RFA,"$700,000","$700,000",1507,Michael Amadio,OTT,24,"C, RW",25,...,13.99,50.76,-,-,-,-,-,-,-,-
1507,NaN,RFA,"$700,000","$700,000",1508,Gustav Forsling,FLA,24,LD,43,...,39.38,50.76,-,-,-,-,-,-,-,-
1508,NaN,UFA,"$700,000","$700,000",1509,David Gust,CAR,26,RW,0,...,0.00,0.00,-,-,-,-,-,-,-,-
1509,NaN,UFA,"$12,500,000","$14,000,000",1,Connor McDavid,EDM,23,C,56,...,43.47,69.16,-,-,-,-,-,-,-,-